# Generated by Django 5.1.4 on 2024-12-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_type',
        ),
    ]
