# Generated by Django 5.1.4 on 2025-01-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0007_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
