# Generated by Django 5.1.4 on 2025-01-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0009_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
